# Generated by Django 4.2.7 on 2024-08-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_quiz_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
