# Generated by Django 4.2.7 on 2024-08-19 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_quizquestion_explanation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizanswer',
            old_name='text',
            new_name='answer_text',
        ),
        migrations.RenameField(
            model_name='quizquestion',
            old_name='text',
            new_name='question_text',
        ),
        migrations.RemoveField(
            model_name='quizanswer',
            name='explanation',
        ),
    ]
