# Generated by Django 4.2.7 on 2024-08-22 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_quizscore_quizattempt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizattempt',
            old_name='max_score',
            new_name='total_score',
        ),
        migrations.RenameField(
            model_name='quizattempt',
            old_name='student',
            new_name='user',
        ),
        migrations.DeleteModel(
            name='QuizScore',
        ),
    ]
