CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
CREATE TABLE IF NOT EXISTS "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE TABLE IF NOT EXISTS "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE TABLE IF NOT EXISTS "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE TABLE IF NOT EXISTS "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "userauths_user_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" bigint NOT NULL REFERENCES "userauths_user" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "userauths_user_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" bigint NOT NULL REFERENCES "userauths_user" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "userauths_profile" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "image" varchar(100) NULL, "full_name" varchar(100) NOT NULL, "country" varchar(100) NULL, "about" text NULL, "date" datetime NOT NULL, "user_id" bigint NOT NULL UNIQUE REFERENCES "userauths_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "userauths_user_groups_user_id_group_id_e032b670_uniq" ON "userauths_user_groups" ("user_id", "group_id");
CREATE INDEX "userauths_user_groups_user_id_70ad3415" ON "userauths_user_groups" ("user_id");
CREATE INDEX "userauths_user_groups_group_id_2bd3d457" ON "userauths_user_groups" ("group_id");
CREATE UNIQUE INDEX "userauths_user_user_permissions_user_id_permission_id_5423ee7a_uniq" ON "userauths_user_user_permissions" ("user_id", "permission_id");
CREATE INDEX "userauths_user_user_permissions_user_id_7dc84ca3" ON "userauths_user_user_permissions" ("user_id");
CREATE INDEX "userauths_user_user_permissions_permission_id_0e980ebe" ON "userauths_user_user_permissions" ("permission_id");
CREATE TABLE IF NOT EXISTS "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL REFERENCES "userauths_user" ("id") DEFERRABLE INITIALLY DEFERRED, "action_time" datetime NOT NULL);
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE TABLE IF NOT EXISTS "api_cartorder" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "sub_total" decimal NOT NULL, "tax_fee" decimal NOT NULL, "total" decimal NOT NULL, "initial_total" decimal NOT NULL, "saved" decimal NOT NULL, "payment_status" varchar(100) NOT NULL, "full_name" varchar(100) NULL, "email" varchar(100) NULL, "country" varchar(100) NULL, "stripe_session_id" varchar(1000) NULL, "oid" varchar(20) NOT NULL UNIQUE, "date" datetime NOT NULL, "student_id" bigint NULL REFERENCES "userauths_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "api_country" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(100) NOT NULL, "tax_rate" integer NOT NULL, "active" bool NOT NULL);
CREATE TABLE IF NOT EXISTS "api_question_answer" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(1000) NULL, "qa_id" varchar(20) NOT NULL UNIQUE, "date" datetime NOT NULL, "course_id" bigint NOT NULL REFERENCES "api_course" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NULL REFERENCES "userauths_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "api_variant" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(1000) NOT NULL, "variant_id" varchar(20) NOT NULL UNIQUE, "date" datetime NOT NULL, "course_id" bigint NOT NULL REFERENCES "api_course" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "api_wishlist" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "course_id" bigint NOT NULL REFERENCES "api_course" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NULL REFERENCES "userauths_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "api_teacher" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "image" varchar(100) NULL, "full_name" varchar(100) NOT NULL, "bio" varchar(100) NULL, "facebook" varchar(200) NULL, "twitter" varchar(200) NULL, "linkedin" varchar(200) NULL, "about" text NULL, "country" varchar(100) NULL, "user_id" bigint NOT NULL UNIQUE REFERENCES "userauths_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "api_review" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "review" text NOT NULL, "rating" integer NOT NULL, "reply" varchar(1000) NULL, "active" bool NOT NULL, "date" datetime NOT NULL, "course_id" bigint NOT NULL REFERENCES "api_course" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NULL REFERENCES "userauths_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "api_question_answer_message" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "message" text NULL, "qam_id" varchar(20) NOT NULL UNIQUE, "qa_id" varchar(20) NOT NULL UNIQUE, "date" datetime NOT NULL, "course_id" bigint NOT NULL REFERENCES "api_course" ("id") DEFERRABLE INITIALLY DEFERRED, "question_id" bigint NOT NULL REFERENCES "api_question_answer" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NULL REFERENCES "userauths_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "api_notification" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "type" varchar(100) NOT NULL, "seen" bool NOT NULL, "date" datetime NOT NULL, "order_id" bigint NULL REFERENCES "api_cartorder" ("id") DEFERRABLE INITIALLY DEFERRED, "order_item_id" bigint NULL REFERENCES "api_cartorderitem" ("id") DEFERRABLE INITIALLY DEFERRED, "review_id" bigint NULL REFERENCES "api_review" ("id") DEFERRABLE INITIALLY DEFERRED, "teacher_id" bigint NULL REFERENCES "api_teacher" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NULL REFERENCES "userauths_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "api_note" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(1000) NULL, "note" text NOT NULL, "note_id" varchar(20) NOT NULL UNIQUE, "date" datetime NOT NULL, "course_id" bigint NOT NULL REFERENCES "api_course" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NULL REFERENCES "userauths_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "api_enrolledcourse" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "enrollment_id" varchar(20) NOT NULL UNIQUE, "date" datetime NOT NULL, "course_id" bigint NOT NULL REFERENCES "api_course" ("id") DEFERRABLE INITIALLY DEFERRED, "order_item_id" bigint NOT NULL REFERENCES "api_cartorderitem" ("id") DEFERRABLE INITIALLY DEFERRED, "teacher_id" bigint NULL REFERENCES "api_teacher" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NULL REFERENCES "userauths_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "api_question_answer_course_id_c6149145" ON "api_question_answer" ("course_id");
CREATE INDEX "api_question_answer_user_id_ad2ae681" ON "api_question_answer" ("user_id");
CREATE INDEX "api_variant_course_id_f87819f3" ON "api_variant" ("course_id");
CREATE INDEX "api_wishlist_course_id_3b316064" ON "api_wishlist" ("course_id");
CREATE INDEX "api_wishlist_user_id_798e25cf" ON "api_wishlist" ("user_id");
CREATE INDEX "api_review_course_id_5f659848" ON "api_review" ("course_id");
CREATE INDEX "api_review_user_id_8bf97ad4" ON "api_review" ("user_id");
CREATE INDEX "api_question_answer_message_course_id_efb764c7" ON "api_question_answer_message" ("course_id");
CREATE INDEX "api_question_answer_message_question_id_f3cec850" ON "api_question_answer_message" ("question_id");
CREATE INDEX "api_question_answer_message_user_id_f9eda61f" ON "api_question_answer_message" ("user_id");
CREATE INDEX "api_notification_order_id_cf1b41a9" ON "api_notification" ("order_id");
CREATE INDEX "api_notification_order_item_id_bbc80d85" ON "api_notification" ("order_item_id");
CREATE INDEX "api_notification_review_id_6843e93e" ON "api_notification" ("review_id");
CREATE INDEX "api_notification_teacher_id_05813800" ON "api_notification" ("teacher_id");
CREATE INDEX "api_notification_user_id_6cede59e" ON "api_notification" ("user_id");
CREATE INDEX "api_note_course_id_970c70ef" ON "api_note" ("course_id");
CREATE INDEX "api_note_user_id_ffcd573e" ON "api_note" ("user_id");
CREATE INDEX "api_enrolledcourse_course_id_8ca168e7" ON "api_enrolledcourse" ("course_id");
CREATE INDEX "api_enrolledcourse_order_item_id_6a7607b9" ON "api_enrolledcourse" ("order_item_id");
CREATE INDEX "api_enrolledcourse_teacher_id_a815ae51" ON "api_enrolledcourse" ("teacher_id");
CREATE INDEX "api_enrolledcourse_user_id_07844dd2" ON "api_enrolledcourse" ("user_id");
CREATE TABLE IF NOT EXISTS "api_coupon" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "code" varchar(50) NOT NULL, "discount" integer NOT NULL, "active" bool NOT NULL, "date" datetime NOT NULL, "teacher_id" bigint NULL REFERENCES "api_teacher" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "api_coupon_used_by" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "coupon_id" bigint NOT NULL REFERENCES "api_coupon" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL REFERENCES "userauths_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "api_completedlesson" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "date" datetime NOT NULL, "course_id" bigint NOT NULL REFERENCES "api_course" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NULL REFERENCES "userauths_user" ("id") DEFERRABLE INITIALLY DEFERRED, "variant_item_id" bigint NOT NULL REFERENCES "api_variantitem" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "api_certificate" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "certificate_id" varchar(20) NOT NULL UNIQUE, "date" datetime NOT NULL, "course_id" bigint NOT NULL REFERENCES "api_course" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NULL REFERENCES "userauths_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "api_coupon_teacher_id_8735e7e7" ON "api_coupon" ("teacher_id");
CREATE UNIQUE INDEX "api_coupon_used_by_coupon_id_user_id_369bb1b6_uniq" ON "api_coupon_used_by" ("coupon_id", "user_id");
CREATE INDEX "api_coupon_used_by_coupon_id_b0ff4d2c" ON "api_coupon_used_by" ("coupon_id");
CREATE INDEX "api_coupon_used_by_user_id_bb2faa26" ON "api_coupon_used_by" ("user_id");
CREATE INDEX "api_completedlesson_course_id_ef9a4c64" ON "api_completedlesson" ("course_id");
CREATE INDEX "api_completedlesson_user_id_456e8281" ON "api_completedlesson" ("user_id");
CREATE INDEX "api_completedlesson_variant_item_id_4657f2bd" ON "api_completedlesson" ("variant_item_id");
CREATE INDEX "api_certificate_course_id_5f6fbe36" ON "api_certificate" ("course_id");
CREATE INDEX "api_certificate_user_id_9dca2b9e" ON "api_certificate" ("user_id");
CREATE TABLE IF NOT EXISTS "api_cartorder_coupons" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "cartorder_id" bigint NOT NULL REFERENCES "api_cartorder" ("id") DEFERRABLE INITIALLY DEFERRED, "coupon_id" bigint NOT NULL REFERENCES "api_coupon" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "api_cartorder_teachers" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "cartorder_id" bigint NOT NULL REFERENCES "api_cartorder" ("id") DEFERRABLE INITIALLY DEFERRED, "teacher_id" bigint NOT NULL REFERENCES "api_teacher" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "api_cartorder_coupons_cartorder_id_coupon_id_a88d6281_uniq" ON "api_cartorder_coupons" ("cartorder_id", "coupon_id");
CREATE INDEX "api_cartorder_coupons_cartorder_id_5f10f45f" ON "api_cartorder_coupons" ("cartorder_id");
CREATE INDEX "api_cartorder_coupons_coupon_id_61cc4f48" ON "api_cartorder_coupons" ("coupon_id");
CREATE INDEX "api_cartorder_student_id_cde527dd" ON "api_cartorder" ("student_id");
CREATE UNIQUE INDEX "api_cartorder_teachers_cartorder_id_teacher_id_07e22475_uniq" ON "api_cartorder_teachers" ("cartorder_id", "teacher_id");
CREATE INDEX "api_cartorder_teachers_cartorder_id_769d3762" ON "api_cartorder_teachers" ("cartorder_id");
CREATE INDEX "api_cartorder_teachers_teacher_id_b251a042" ON "api_cartorder_teachers" ("teacher_id");
CREATE TABLE IF NOT EXISTS "api_cart" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "price" decimal NOT NULL, "tax_fee" decimal NOT NULL, "total" decimal NOT NULL, "country" varchar(100) NULL, "date" datetime NOT NULL, "course_id" bigint NOT NULL REFERENCES "api_course" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NULL REFERENCES "userauths_user" ("id") DEFERRABLE INITIALLY DEFERRED, "cart_id" varchar(20) NOT NULL);
CREATE INDEX "api_cart_course_id_8b4a0104" ON "api_cart" ("course_id");
CREATE INDEX "api_cart_user_id_79972181" ON "api_cart" ("user_id");
CREATE TABLE IF NOT EXISTS "api_cartorderitem" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "tax_fee" decimal NOT NULL, "total" decimal NOT NULL, "initial_total" decimal NOT NULL, "saved" decimal NOT NULL, "applied_coupon" bool NOT NULL, "oid" varchar(20) NOT NULL UNIQUE, "date" datetime NOT NULL, "course_id" bigint NOT NULL REFERENCES "api_course" ("id") DEFERRABLE INITIALLY DEFERRED, "order_id" bigint NOT NULL REFERENCES "api_cartorder" ("id") DEFERRABLE INITIALLY DEFERRED, "teacher_id" bigint NOT NULL REFERENCES "api_teacher" ("id") DEFERRABLE INITIALLY DEFERRED, "price" decimal NOT NULL);
CREATE INDEX "api_cartorderitem_course_id_886a70db" ON "api_cartorderitem" ("course_id");
CREATE INDEX "api_cartorderitem_order_id_b67acd88" ON "api_cartorderitem" ("order_id");
CREATE INDEX "api_cartorderitem_teacher_id_4ef3e069" ON "api_cartorderitem" ("teacher_id");
CREATE TABLE IF NOT EXISTS "api_cartorderitem_coupons" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "cartorderitem_id" bigint NOT NULL REFERENCES "api_cartorderitem" ("id") DEFERRABLE INITIALLY DEFERRED, "coupon_id" bigint NOT NULL REFERENCES "api_coupon" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "api_cartorderitem_coupons_cartorderitem_id_coupon_id_b8bab7e3_uniq" ON "api_cartorderitem_coupons" ("cartorderitem_id", "coupon_id");
CREATE INDEX "api_cartorderitem_coupons_cartorderitem_id_2d3b58a0" ON "api_cartorderitem_coupons" ("cartorderitem_id");
CREATE INDEX "api_cartorderitem_coupons_coupon_id_cfce253e" ON "api_cartorderitem_coupons" ("coupon_id");
CREATE TABLE IF NOT EXISTS "api_variantitem" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(1000) NOT NULL, "description" text NULL, "duration" bigint NULL, "content_duration" varchar(1000) NULL, "preview" bool NOT NULL, "variant_item_id" varchar(20) NOT NULL UNIQUE, "date" datetime NOT NULL, "variant_id" bigint NOT NULL REFERENCES "api_variant" ("id") DEFERRABLE INITIALLY DEFERRED, "file" varchar(100) NULL);
CREATE INDEX "api_variantitem_variant_id_012af230" ON "api_variantitem" ("variant_id");
CREATE TABLE IF NOT EXISTS "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
CREATE TABLE IF NOT EXISTS "token_blacklist_blacklistedtoken" ("blacklisted_at" datetime NOT NULL, "token_id" bigint NOT NULL UNIQUE REFERENCES "token_blacklist_outstandingtoken" ("id") DEFERRABLE INITIALLY DEFERRED, "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT);
CREATE TABLE IF NOT EXISTS "token_blacklist_outstandingtoken" ("token" text NOT NULL, "created_at" datetime NULL, "expires_at" datetime NOT NULL, "user_id" bigint NULL REFERENCES "userauths_user" ("id") DEFERRABLE INITIALLY DEFERRED, "jti" varchar(255) NOT NULL UNIQUE, "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT);
CREATE INDEX "token_blacklist_outstandingtoken_user_id_83bc629a" ON "token_blacklist_outstandingtoken" ("user_id");
CREATE TABLE IF NOT EXISTS "userauths_user" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "username" varchar(100) NOT NULL UNIQUE, "email" varchar(254) NOT NULL UNIQUE, "full_name" varchar(100) NOT NULL UNIQUE, "otp" varchar(100) NULL, "refresh_token" varchar(1000) NULL);
CREATE TABLE IF NOT EXISTS "api_course" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "file" varchar(100) NULL, "image" varchar(100) NULL, "description" text NULL, "price" decimal NOT NULL, "language" varchar(100) NOT NULL, "level" varchar(100) NOT NULL, "platform_status" varchar(100) NOT NULL, "teacher_course_status" varchar(100) NOT NULL, "featured" bool NOT NULL, "course_id" varchar(20) NOT NULL UNIQUE, "slug" varchar(255) NOT NULL UNIQUE, "date" datetime NOT NULL, "category_id" bigint NULL REFERENCES "api_category" ("id") DEFERRABLE INITIALLY DEFERRED, "teacher_id" bigint NOT NULL REFERENCES "api_teacher" ("id") DEFERRABLE INITIALLY DEFERRED, "title" varchar(255) NOT NULL);
CREATE INDEX "api_course_category_id_91393008" ON "api_course" ("category_id");
CREATE INDEX "api_course_teacher_id_e24f8110" ON "api_course" ("teacher_id");
CREATE TABLE IF NOT EXISTS "api_category" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(100) NOT NULL, "image" varchar(100) NULL, "active" bool NOT NULL, "slug" varchar(50) NULL UNIQUE);
CREATE UNIQUE INDEX "api_enrolledcourse_course_id_user_id_d4e7c17c_uniq" ON "api_enrolledcourse" ("course_id", "user_id");
CREATE TABLE IF NOT EXISTS "api_userquizresponse" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "is_correct" bool NOT NULL, "date_answered" datetime NOT NULL, "question_id" bigint NOT NULL REFERENCES "api_question" ("id") DEFERRABLE INITIALLY DEFERRED, "quiz_id" bigint NOT NULL REFERENCES "api_quiz" ("id") DEFERRABLE INITIALLY DEFERRED, "selected_answer_id" bigint NOT NULL REFERENCES "api_answer" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL REFERENCES "userauths_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "api_userquizresponse_user_id_quiz_id_question_id_8e360add_uniq" ON "api_userquizresponse" ("user_id", "quiz_id", "question_id");
CREATE INDEX "api_userquizresponse_question_id_fba132f2" ON "api_userquizresponse" ("question_id");
CREATE INDEX "api_userquizresponse_quiz_id_e5bb9885" ON "api_userquizresponse" ("quiz_id");
CREATE INDEX "api_userquizresponse_selected_answer_id_2fb7ba37" ON "api_userquizresponse" ("selected_answer_id");
CREATE INDEX "api_userquizresponse_user_id_8146e063" ON "api_userquizresponse" ("user_id");
CREATE TABLE IF NOT EXISTS "api_question" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "text" text NOT NULL, "quiz_id" bigint NOT NULL REFERENCES "api_quiz" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "api_answer" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "text" text NOT NULL, "is_correct" bool NOT NULL, "question_id" bigint NOT NULL REFERENCES "api_question" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "api_question_quiz_id_72d0bb99" ON "api_question" ("quiz_id");
CREATE INDEX "api_answer_question_id_b279e2b5" ON "api_answer" ("question_id");
CREATE UNIQUE INDEX "api_notification_teacher_id_order_id_order_item_id_type_0a01cf14_uniq" ON "api_notification" ("teacher_id", "order_id", "order_item_id", "type");
CREATE TABLE IF NOT EXISTS "api_quizquestion" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "question_text" varchar(1000) NOT NULL, "score" integer unsigned NOT NULL CHECK ("score" >= 0), "quiz_id" bigint NOT NULL REFERENCES "api_quiz" ("id") DEFERRABLE INITIALLY DEFERRED, "explanation" text NULL);
CREATE TABLE IF NOT EXISTS "api_quizanswer" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "answer_text" varchar(1000) NOT NULL, "is_correct" bool NOT NULL, "question_id" bigint NOT NULL REFERENCES "api_quizquestion" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "api_quizquestion_quiz_id_84ca9fef" ON "api_quizquestion" ("quiz_id");
CREATE INDEX "api_quizanswer_question_id_5d0a8b92" ON "api_quizanswer" ("question_id");
CREATE TABLE IF NOT EXISTS "api_quiz" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(255) NOT NULL, "description" text NULL, "created_at" datetime NOT NULL, "course_id" bigint NOT NULL REFERENCES "api_course" ("id") DEFERRABLE INITIALLY DEFERRED, "status" varchar(10) NOT NULL);
CREATE INDEX "api_quiz_course_id_0e63b074" ON "api_quiz" ("course_id");
CREATE TABLE IF NOT EXISTS "api_quizattempt" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "score" decimal NOT NULL, "date_taken" datetime NOT NULL, "quiz_id" bigint NOT NULL REFERENCES "api_quiz" ("id") DEFERRABLE INITIALLY DEFERRED, "total_score" decimal NOT NULL, "user_id" bigint NOT NULL REFERENCES "userauths_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "api_quizattempt_quiz_id_4b081504" ON "api_quizattempt" ("quiz_id");
CREATE INDEX "api_quizattempt_user_id_d9ad3032" ON "api_quizattempt" ("user_id");
